// All the main()s in fail/ should eventually panic!

fn main()
	assert(0)

